### ISSUE TITLE
平均單卡最低售價都變成美金了

### ISSUE THREAD

**Issue by bjiyxo** [www10177/SteamCardsHelper#1]
如題，可以幫忙修正嗎？

**Comment by www10177** [comment]
我這邊看是OK的(有登入)
不確定是否是因為沒有登入/無痕之類的直接進到steam market，它預設會顯示美金
雖然我剛剛測試顯示是正常的

可以幫我試點擊開啟市場頁面show出來的試twd or usd嗎?
以及你帳戶的顯示幣別是否為台幣

**Comment by bjiyxo** [comment]
登入後就正常了，Thx。
不過有可能達成不登入就能看到台幣的情況嗎？

**Comment by www10177** [comment]
主要是我在這邊的作法是直接去撈steam market資料[like this](https://steamcommunity.com/market/search?category_753_Game%5B%5D=tag_app_420110&category_753_cardborder%5B%5D=tag_cardborder_0&category_753_item_class%5B%5D=tag_item_class_2&appid=753)
在url上沒看到可以指定國家/貨幣的參數
可能得在研究下steam透過甚麼判斷的(如果有在header,cookie...裡之類的)
如果他是透過登入才判斷國家在現有的作法之上大概達不到目標XD

印象中透過API是可以指定貨幣別的，不過之前試API撈太多次會被禁止存取
